version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nextjs_prisma?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # For development, you might want to use:
    # command: sh -c "npx prisma migrate dev --name init && npm run dev"
    # For production:
    command: sh -c "npx prisma migrate deploy && node server.js"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs_prisma
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Optional: Add Prisma Studio for database management
  prisma-studio:
    image: node:18-alpine
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555
    ports:
      - '5555:5555'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nextjs_prisma?schema=public

volumes:
  postgres_data:
