apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nextjs-prisma
data:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: http://localhost:3000
  DATABASE_URL: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres:5432/nextjs_prisma?schema=public"
