apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nextjs-prisma
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_USER: cG9zdGdyZXM=      # base64 encoded 'postgres'
